### ISSUE TITLE
屏幕外的dom无法截图

### ISSUE THREAD

**Issue by zzz999** [wangzongming/web-screenshot#1]
![image](https://github.com/user-attachments/assets/48702c6b-7c83-468b-80a9-4d39dce5dd00)
![image](https://github.com/user-attachments/assets/1624447a-3f03-4c8e-9e35-8ab966cd5822)

**Comment by wangzongming** [comment]
是的，屏幕之外的无法截图。原理是对整个tab页面进行截图，然后在进行裁剪。
